meta_product_name: "Travel Maker"
meta_title: "Travel Maker - create and share your trip"
meta_description: "Plan your hotels, activity, transport... Define a budget per day and share it with your travel partner in just a few clicks."
meta_image: "meta_travel_maker.png" # should exist in `app/assets/images/`
